### ISSUE TITLE
Object detection experiments

### ISSUE THREAD

**Issue by jaycheney** [valeoai/SLidR#13]
Could you kindly share the code via email used to finetune object detection models from OpenPCDet? I'm still reproducing the results of SLidR. It'll help me a lot.
Originally posted by @CSautier in https://github.com/valeoai/SLidR/issues/3#issuecomment-1193282244.

**Comment by CSautier** [comment]
I sent it by email

**Comment by BoPang1996** [comment]
@JakeVander I need the detection code to reproduce Slidr. Would you kindly send the code to me? (pangbo@sjtu.edu.cn)
