### ISSUE TITLE
Object detection experiments

### ISSUE THREAD

**Issue by BoPang1996** [valeoai/SLidR#15]
Could you kindly share the code via email (pangbo@sjtu.edu.cn) used to finetune object detection models from OpenPCDet? I'm still reproducing the results of SLidR. It'll help me a lot.
Originally posted by @CSautier in #3 (comment).

**Comment by CSautier** [comment]
Hi, sorry for the late reply, I sent you what you requested, let's continue this conversation by email if you need assistance.

**Comment by youquanl** [comment]
Hi! @BoPang1996 @CSautier.  I am also trying to reproduce the results of SLidR. I so appreciate it if you guys can share codes by email (yliu@studenten.hs-bremerhaven.de) that are used to fine-tune the object detection models.
