### ISSUE TITLE
detection on kitti using Minkowski SR-Unet

### ISSUE THREAD

**Issue by Vitarie** [valeoai/SLidR#18]
Could you kindly share the code via email used to finetune object detection models from OpenPCDet? I'm specifically interested in PointRCNN using Minkowski-UNet backbone. 

 _posted by @CSautier in #7_

**Comment by CSautier** [comment]
Hi, I couldn't find your email address, but here is the code for OpenPCDet [https://drive.google.com/file/d/1zeuXMOJLVz4yCwZ2FDiH8ANbw6LJ7BJq/view?usp=sharing](https://drive.google.com/file/d/1zeuXMOJLVz4yCwZ2FDiH8ANbw6LJ7BJq/view?usp=sharing)
You might need a proper fork of OpenPCDet to run it, and I apologize if the code is not easy to use, it was not intended to be released.

**Comment by Vitarie** [comment]
Thanks！

**Comment by mu-cai** [comment]
@CSautier I am also interested in object detection using Minkowski-UNet backbone. But Google drive link expired, can you send another one? Thanks!
