### ISSUE TITLE
Question about reproducing experiment

### ISSUE THREAD

**Issue by opjang5** [valeoai/SLidR#2]
Hi, I have reproduced your experiment with two 3090 GPUs. However, My results on nuScenes with 1% labeled data are much lower than yours. Here are my detailed results. Could you tell me your detailed configuration of experiments?
Per class IoU:
barrier              - 0.000
bicycle              - 0.000
bus                  - 0.073
car                  - 0.709
construction_vehicle - 0.011
motorcycle           - 0.000
pedestrian           - 0.424
traffic_cone         - 0.000
trailer              - 0.222
truck                - 0.311
driveable_surface    - 0.928
other_flat           - 0.162
sidewalk             - 0.540
terrain              - 0.593manmade              - 0.802
vegetation           - 0.822

mIoU: 0.34969189763069153
fwIoU: 0.7560390830039978

**Comment by CSautier** [comment]
Hi, thank you for your interest in SLidR!
The problem you had seem similar to that of #1. There was indeed an issue with the configurations to reproduce results: the learning rates were those of the linear probing which resulted in lower than expected results.
I have pushed yesterday a fix to use by default the correct config for this specific experiment. Note that the learning rates have been grid search on our mini trainval split for the specific pre-training weights provided. If you redid the pre-training, you might need to tune them to reach best performances.
