### ISSUE TITLE
How to use this project to complete the distillation of target detection method

### ISSUE THREAD

**Issue by VsionQing** [valeoai/SLidR#23]
For example, the distillation of PVRCNN model mentioned in the paper

**Comment by CSautier** [comment]
Hi,
I'm not exactly sure I understand your question. PVRCNN is not mentionned in the paper at all. This repo still provides experimental code to pre-train a PVRCNN encoder, with a config file in [slidr_voxelnet.yaml](https://github.com/valeoai/SLidR/blob/main/config/slidr_voxelnet.yaml)
