### ISSUE TITLE
Could you please share the visualised code?

### ISSUE THREAD

**Issue by jaycheney** [valeoai/SLidR#25]
Hello,
I noticed that the SLidR flow chart has been updated on the official website of your lab. Could you please share the visualised code?
Thanks！
https://valeoai.github.io/blog/2022/06/14/valeoai-at-cvpr-2022.html

**Comment by CSautier** [comment]
Hello,
I won't be able to do it in the next few days. I would have to see if the code works with the release version of SLidR, but if the code does not require too much adaptation, I will push it in the repo.

**Comment by CSautier** [comment]
I pushed the visualisation code, so that anyone can reproduce visualizations similar to those in the article and poster of SLidR.
