### ISSUE TITLE
Can not reproduce the results in PV-RCNN for object detection. Voxel size different?

### ISSUE THREAD

**Issue by mu-cai** [valeoai/SLidR#28]
Hi authors,
I tried to use your provided checkpoint to evaluate object detection performance. I found that I got a worse result in PV-RCNN object detection compared to the results claimed in your GitHub (even compared with training from scrtch).

Here I use the official code in OpenPCdet, where the voxel size is [0.5, 0.5, 1], (your pertaining voxel size is [1, 1, 2]).

Maybe you can also send the code of object detection to me? ([mucai@cs.wisc.edu](mailto:mucai@cs.wisc.edu)).
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/65588556/218875122-38c14acc-70d2-412b-9050-64497c16ba38.png">

**Comment by CSautier** [comment]
I cannot really comment specifically on this training, but in general object detection results are extremely noisy (std > 1mAP). This experiment was never even included in the article. As for voxel size and other hyperparameters I seem to remember that we kept everything consistent with default OpenPCDet parameters for PV-RCNN on KITTI.
