### ISSUE TITLE
Downstream Object Detection Experiments

### ISSUE THREAD

**Issue by youquanl** [valeoai/SLidR#29]
Could you kindly share the code via email(yliu@studenten.hs-bremerhaven.de) used to finetune object detection models from OpenPCDet? I'm still reproducing the results of SLidR. It'll help me a lot.

**Comment by CSautier** [comment]
For future reference, I uploaded the (completely uncurated) object detection code as well as some weights on this link [https://drive.google.com/file/d/1KmpnlSFR4kHbaRNJuVqJkGG_b4NzyT_2/view?usp=sharing](https://drive.google.com/file/d/1KmpnlSFR4kHbaRNJuVqJkGG_b4NzyT_2/view?usp=sharing)

**Comment by youquanl** [comment]
Got it! Thanks a lot.
