### ISSUE TITLE
Setting of the fraction of the training labels

### ISSUE THREAD

**Issue by gbliao** [valeoai/SLidR#30]
Could you kindly share the setting used to finetune object detection models with a fraction of the training labels, e.g., 1%, 5%, or 10% on the Nuscenes dataset? It'll help me a lot.

**Comment by CSautier** [comment]
Hi, sorry for the delay.

I think there is a confusion here as we did not finetune object detection on nuScenes. We finetuned semantic segmentation on both nuScenes and SemanticKITTI, and object detection on KITTI only.

**Comment by gbliao** [comment]
Thanks for your reply.
