### ISSUE TITLE
Object detection experiments

### ISSUE THREAD

**Issue by TimGor1997** [valeoai/SLidR#32]
Could you kindly share the code via email used to finetune object detection models from OpenPCDet? 
My email address is 595603009@qq.com
Thank you so much!

**Comment by CSautier** [comment]
Here is a google drive link containing the raw code I had used at the time (related: Issue #29). However it is certainly not easy to use as it was not thought to be shared later https://drive.google.com/file/d/1KmpnlSFR4kHbaRNJuVqJkGG_b4NzyT_2/view?usp=sharing
