### ISSUE TITLE
Downstream.py bug: RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by Stephanie-Shen324** [valeoai/SLidR#9]
Hi, 
I am currently reproducing downstream(segmentation with nuscenes) results from your given checkpoints. I am experiencing this runtime error: grad can be implicitly created only for scalar outputs.

Have you seen this error? 

The command used is : python downstream.py --cfg_file="config/semseg_nuscenes.yaml" --pretraining_path="provide_model/minkunet_slidr_1gpu.pt"

The full error message is as in the file.
[error.txt](https://github.com/valeoai/SLidR/files/9336413/error.txt)

**Comment by CSautier** [comment]
Hi,
This is most likely an issue with pytorch_lightning. Can you verify that you have version 1.4.0 installed?
Otherwise it could mean that the loss isn't a scalar, which it should be. Are you running the code with multiple GPUs?

**Comment by Stephanie-Shen324** [comment]
Thank you for replying. This issue was solved by using cuda10.2 instead of 11.1
